### ISSUE TITLE
Mapa carga continuamente.

### ISSUE THREAD

**Issue by andrescampill** [youngsdeveloper/aeropuerto-bus-realtime#2]
Al entrar a la página, puedes encontrar que el mapa se queda cargando de forma continua, no aparece el mapa, aunque la API de Interbus (www.interbusmurcia.es/ext.aeropuerto.php) muestra unas coordenadas.
La consola muestra los siguientes errores:
![image](https://user-images.githubusercontent.com/67756014/211053948-071f6a9b-ceb4-4c7a-adc6-81047c8a600d.png)

Desconozco si Interbus sigue prestando el servicio, si lo presta otro grupo o incluso si la línea ya no existe.

**Comment by KikeOnRails** [comment]
Hola. El problema es que no podía usar la API de Interbus directamente por el bloque de las CORS.

Por eso hice un servidor para evitar el bloqueo de las CORS, pero ese servidor ahora mismo no está funcionando.

El servicio de bus del aeropuerto dejo de funcionar desde este verano, así que se muestra las coordenadas de otro bus de otras líneas.

Intentaré volver a poner el funcionamiento del servidor para que vuelva a funcionar.

**Comment by andrescampill** [comment]
Muchas gracias por la respuesta.
Es entendible que la parte de back end no esté ya en funcionamiento debido a la inexistencia acutal de la línea. 
Este proyecto al igual (al igual que el de Bus Murcia) me parecen muy interesantes.

**Comment by KikeOnRails** [comment]
Buenas.

El proyecto vuelve a funcionar de nuevo, ya vuelve a cargar en el mapa la ubicación del autobús en tiempo real.

También he añadido un aviso para avisar a los usuarios de que no se trata de la linea del aeropuerto, sino de otras lineas de la Región que usan ese mismo bus.

Ha sido solucionado en 7ed806e32b18945bf45d2f68e1a72b33f5c9bb57

¡Un saludo y gracias por el aviso!
